//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Model.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игра окончена. Пожалуйста, введите ваше имя и нажмите &quot;Enter&quot;.
        /// </summary>
        internal static string GameOver {
            get {
                return ResourceManager.GetString("GameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ╔══╡
        ///║    ╥    ╔══╗ ╔══╗ ╔══╗ ╥  ╥
        ///╠══╡ ║    ║  ║ ║  ║ ║  ║ ║  ║
        ///║    ║    ╠══╣ ╠══╝ ╠══╝ ╚══╣
        ///╨    ╚══╡ ╨  ╨ ╨    ╨    ╞══╝
        ///      ╔══╗ ╥
        ///      ╠══╝ ╨         ╥
        ///      ╠══╗ ╥ ╔══╗ ╔══╣
        ///      ║  ║ ║ ║  ╨ ║  ║
        ///      ╚══╝ ╨ ╨    ╚══╝.
        /// </summary>
        internal static string Heading {
            get {
                return ResourceManager.GetString("Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инструкция:
        ///
        ///Меню:
        ///Для выбора пункта меню применяется клавиша &quot;ENTER&quot;.
        ///
        ///Пункт меню:
        ///Для возврата из пунктов меню &quot;Рекорды&quot; и &quot;Инструкция&quot; используеются клавиши &quot;ESC&quot; и &quot;ENTER&quot;.
        ///
        ///Игра:
        ///Для управления игрой применяются клавиши &quot;W&quot;, &quot;SPACE&quot; и &quot;UP&quot;. Для досрочного завершения игры (завершения игры без сохранения рекорда) используется клавиша &quot;ESC&quot;..
        /// </summary>
        internal static string Instruction {
            get {
                return ResourceManager.GetString("Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на record.rec.
        /// </summary>
        internal static string RecordPath {
            get {
                return ResourceManager.GetString("RecordPath", resourceCulture);
            }
        }
    }
}
